# Generated by Django 4.2.10 on 2024-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[('0', 'Черновик'), ('1', 'Опубликован')], default='0'),
        ),
    ]
